full_rebuild: true
name: itsCoder
description: it's coder
destination: jekyllbuild
url: #place url
baseurl: #place folder name if site is served in subfolder
permalink: /:title/
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
gems: [jekyll-paginate]
#tumblr: "#"
#pinterest: "#"
#instagram: "#"
#twitter: "#"
#facebook: "#"
#youtube: "#"
#vimeo: "#"
#soundcloud: "#"
github: "https://github.com/itsCoder"
rss: "/feed"
members: "/members"

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
markdown: kramdown
